[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"
  environment = { GEMINI_API_KEY = "AIzaSyDQPOb7SRYDVunXHNfmZO8hwzt1ZmCFGv4" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
